### Test delete request.
DELETE http://localhost:3001/api/persons/3 http//1.1

### Test Post request, this should work
POST http://localhost:3001/api/persons http//1.1
Content-Type: application/json

 {
    "person": "Simple",
    "number": "123-546-7999"
 }

### Test post request, missing name. Expecting failure.
POST http://localhost:3001/api/persons http//1.1
Content-Type: application/json

 {
    "number": "123-546-7999"
 }
 
### Test post request, missing number. Expecting failure
POST http://localhost:3001/api/persons http//1.1
Content-Type: application/json

 {
    "person": "Simple"
 }

### Test get all request. 
 GET http://localhost:3001/api/persons http//1.1

 