### Test Post request, this should work
POST http://localhost:3003/api/blogs http//1.1
Content-Type: application/json

 {
    "title": "10 speedrunning tricks.",
    "author": "Simple",
    "url": "fake_url",
    "likes": 310
 }

### Test Delete request
DELETE http://localhost:3003/api/blogs/69ea54a222c0294ae7239e24 http//1.1


### Test new user request
POST http://localhost:3003/api/users http//1.1
Content-Type: application/json

{
  "username": "bbBuilder2",
  "password": "Can we build it?",
  "name": "Bob"
}